/**
 * Rich-text editor bundle.
 *
 * ProseMirror, the engine this is built on, has circular imports and CommonJS
 * interop that a browser cannot resolve as native modules, so it has to be
 * bundled. It is the only file in the app that is.
 *
 * Generated by scripts/build-editor.mjs — edit this file, then run
 * `npm run build:editor` to regenerate it.
 *
 * The API is intentionally narrow:
 *
 *   createEditor(host, {content, placeholder, onChange}) -> handle | null
 *
 * `onChange` receives plain text on every document change. The composer keeps its
 * own plain-text mirror because a mail message needs a text alternative for
 * clients that will not render HTML at all, and deriving one from HTML at send
 * time is strictly worse than maintaining it as you type.
 *
 * Marks that are active are exposed through `isActive(name)` so the composer can
 * reflect state without reaching into ProseMirror's internals.
 */

import { Extension, Editor } from '@tiptap/core';
import { Plugin, PluginKey } from '@tiptap/pm/state';
import { Decoration, DecorationSet } from '@tiptap/pm/view';
import StarterKit from '@tiptap/starter-kit';

/** Marks and nodes the toolbar exposes, in display order. */
export const TOOLBAR = [
  { name: 'bold', label: 'Bold', kind: 'mark' },
  { name: 'italic', label: 'Italic', kind: 'mark' },
  { name: 'strike', label: 'Strikethrough', kind: 'mark' },
  { name: 'code', label: 'Inline code', kind: 'mark' },
  { name: 'bulletList', label: 'Bulleted list', kind: 'node' },
  { name: 'orderedList', label: 'Numbered list', kind: 'node' },
  { name: 'blockquote', label: 'Quote', kind: 'node' },
  { name: 'link', label: 'Insert link', kind: 'node' },
];

const placeholderKey = new PluginKey('composerPlaceholder');

/**
 * Placeholder as a decoration rather than a CSS pseudo-element on the host.
 *
 * A pseudo-element cannot tell an empty document from one whose only content is
 * formatting, and it covers the whole host rather than the first block. As a
 * decoration it applies to the real first block, and only while there is no text.
 */
function placeholderExtension(text) {
  return Extension.create({
    name: 'placeholder',

    addProseMirrorPlugins() {
      return [
        new Plugin({
          key: placeholderKey,
          props: {
            decorations(state) {
              if (!text || state.doc.textContent.length > 0) return null;
              // Must be a DecorationSet, not a plain array of specs: ProseMirror
              // calls `map` on the result while drawing, and an array has none.
              return DecorationSet.create(state.doc, [
                Decoration.node(0, state.doc.content.size, {
                  class: 'editor-placeholder',
                  'data-placeholder': text,
                }),
              ]);
            },
          },
        }),
      ];
    },
  });
}

/**
 * StarterKit, trimmed to what belongs in an email body.
 *
 * A `#` in a message should stay a `#`, and a fenced block should not become a
 * full-width monospace block that reflows badly in most clients.
 */
function extensions({ placeholder }) {
  // Both entries are passed as a flat list rather than merged with `.extend()`.
  // In TipTap 3 a child added through `.extend({extensions: [...]})` on a
  // configured StarterKit is dropped without warning: its `addProseMirrorPlugins`
  // simply never runs, so the placeholder decoration never appears and there is
  // nothing to assert against. A flat array is unambiguous.
  return [
    StarterKit.configure({
      heading: false,
      codeBlock: false,
      horizontalRule: false,
      history: { depth: 100 },
      link: {
        openOnClick: false,
        autolink: true,
        // Anything not http(s) is a live-script or data-exfiltration risk in the
        // recipient's client, so it is constrained here as well as at input time.
        protocols: ['http', 'https'],
        HTMLAttributes: { rel: 'noopener noreferrer nofollow', target: '_blank' },
      },
    }),
    placeholderExtension(placeholder),
  ];
}

/**
 * A chain whose commands are all no-ops.
 *
 * Returned when a command cannot run — most often mid-composition, when an IME
 * is still composing and mutating the document would cancel it. The toolbar can
 * then be written without guarding every control, because a command that cannot
 * apply reports failure instead of raising.
 */
function inertChain() {
  const noop = () => {
    const api = {};
    const chainMethods = [
      'focus',
      'toggleBold',
      'toggleItalic',
      'toggleStrike',
      'toggleCode',
      'toggleBulletList',
      'toggleOrderedList',
      'toggleBlockquote',
      'extendMarkRange',
      'setLink',
      'unsetLink',
      'insertContent',
      'deleteSelection',
    ];
    for (const method of chainMethods) api[method] = () => api;
    api.run = () => false;
    return api;
  };
  return noop();
}

/**
 * Build an editor bound to `host`.
 *
 * Returns null when the editor cannot start, so the caller keeps its textarea.
 * An email client that will not open its composer is a far worse failure than one
 * without formatting, so every failure here is non-fatal by design.
 *
 * @param {HTMLElement} host
 * @param {{content?: string, placeholder?: string, onChange?: (text: string) => void}} opts
 * @returns {object|null}
 */
export function createEditor(host, { content = '', placeholder = '', onChange } = {}) {
  let editor = null;

  try {
    editor = new Editor({
      element: host,
      extensions: extensions({ placeholder }),
      content: content || '',
      // TipTap's own onUpdate fires per transaction; restricting it to document
      // changes keeps selection-only moves from looking like edits to the caller.
      onUpdate: ({ editor: instance }) => {
        onChange?.(instance.getText({ blockSeparator: '\n' }));
      },
      editorProps: {
        attributes: {
          class: 'editor-surface',
          role: 'textbox',
          'aria-multiline': 'true',
          'aria-label': 'Message body',
        },
      },
    });
  } catch {
    // TipTap throws if the element cannot host an editor (detached, or no
    // layout-capable DOM). The composer keeps its textarea.
    return null;
  }

  // Belt and braces: a constructed Editor can still report a dead view in an
  // environment without a real DOM, and the caller's fallback depends on getting
  // null rather than a handle that throws on first use.
  if (!editor?.view) {
    try {
      editor?.destroy?.();
    } catch {
      /* nothing to clean up */
    }
    return null;
  }

  const guard = (fn, fallback) => {
    try {
      const value = fn();
      return value ?? fallback;
    } catch {
      return fallback;
    }
  };

  return {
    isActive: (name) => guard(() => editor.isActive(name), false),
    getAttributes: (name) => guard(() => editor.getAttributes(name), {}),
    chain: () => {
      const chain = guard(() => editor.chain().focus(), null);
      return chain || inertChain();
    },
    getHTML: () => guard(() => editor.getHTML(), ''),
    getText: () => guard(() => editor.getText({ blockSeparator: '\n' }), ''),
    focus: () => guard(() => editor.commands.focus(), undefined),
    on: (...args) => guard(() => editor.on(...args), undefined),
    destroy: () => {
      try {
        editor.destroy();
      } catch {
        /* already destroyed */
      }
    },
  };
}

export { placeholderExtension, extensions };